/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.java858.jpacrud.todoapp.GUI;

import it.java858.jpacrud.todoapp.GUI.CategoriaTM;
import it.java858.jpacrud.todoapp.entity.Categoria;
import it.java858.jpacrud.todoapp.service.CategoriaService;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tss
 */
public class CategoriaCRUD extends javax.swing.JDialog {

    CategoriaTM categoriaTM;

    /**
     * Creates new form CategoriaCRUD
     */
    public CategoriaCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        categoriaTM = new CategoriaTM(CategoriaService.Estrai());
        TblCategorie.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        TblCategorie.setModel(categoriaTM);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblCategorie = new javax.swing.JTable();
        cmdMod = new javax.swing.JButton();
        cmdCan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblCategorie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblCategorie);

        cmdMod.setText("Modifica");
        cmdMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModActionPerformed(evt);
            }
        });

        cmdCan.setText("Cancella");
        cmdCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMod)
                    .addComponent(cmdCan))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCanActionPerformed
        Categoria toRemove;
        toRemove = categoriaTM.get
                (TblCategorie.convertRowIndexToModel(TblCategorie.getSelectedRow()));
        CategoriaService.Elimina(toRemove);
        categoriaTM.changeDATA(CategoriaService.Estrai());
    }//GEN-LAST:event_cmdCanActionPerformed

    private void cmdModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModActionPerformed
    Categoria ToModif;
    ToModif = categoriaTM.get(TblCategorie.convertRowIndexToModel(TblCategorie.getSelectedRow()));
    CategoriaEdit dialog = new CategoriaEdit(this, true, ToModif);
    dialog.setVisible(true);
    categoriaTM.changeDATA(CategoriaService.Estrai());
    }//GEN-LAST:event_cmdModActionPerformed
    private void close() {
        this.setVisible(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblCategorie;
    private javax.swing.JButton cmdCan;
    private javax.swing.JButton cmdMod;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
