/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.java858.jpacrud.todoapp.GUI;

import it.java858.jpacrud.todoapp.entity.Categoria;
import it.java858.jpacrud.todoapp.entity.ToDo;
import it.java858.jpacrud.todoapp.service.event.CategoriaEventListener;
import javax.swing.JOptionPane;

/**
 *
 * @author tss
 */
public class Main extends javax.swing.JFrame  implements CategoriaEventListener{

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnucreacat = new javax.swing.JMenuItem();
        mnugestcat = new javax.swing.JMenuItem();
        mnuToDo = new javax.swing.JMenu();
        mnuCtodo = new javax.swing.JMenuItem();
        mnugestTodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Programma per gestione ToDo e Categorie di ToDo    ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 490, 260));

        jMenu1.setText("File");

        jMenuItem1.setText("Esci");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Categorie");

        mnucreacat.setText("Crea Categoria");
        mnucreacat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucreacatActionPerformed(evt);
            }
        });
        jMenu2.add(mnucreacat);

        mnugestcat.setText("Gestione categorie");
        mnugestcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnugestcatActionPerformed(evt);
            }
        });
        jMenu2.add(mnugestcat);

        jMenuBar1.add(jMenu2);

        mnuToDo.setText("ToDo");

        mnuCtodo.setText("creaToDo");
        mnuCtodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCtodoActionPerformed(evt);
            }
        });
        mnuToDo.add(mnuCtodo);

        mnugestTodo.setText("Gestione ToDo");
        mnugestTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnugestTodoActionPerformed(evt);
            }
        });
        mnuToDo.add(mnugestTodo);

        jMenuBar1.add(mnuToDo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnucreacatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucreacatActionPerformed
        CategoriaEdit Edit = new CategoriaEdit(this, true,new Categoria());
        Edit.setLocationRelativeTo(this);
        Edit.setVisible(true);
        
    }//GEN-LAST:event_mnucreacatActionPerformed

    private void mnugestcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnugestcatActionPerformed
        CategoriaCRUD editcrud = new CategoriaCRUD(this, true);
        editcrud.setLocationRelativeTo(this);
        editcrud.setVisible(true);
    }//GEN-LAST:event_mnugestcatActionPerformed

    private void mnugestTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnugestTodoActionPerformed
       TodoCRUD editTcrud = new TodoCRUD(this, true);
        editTcrud.setLocationRelativeTo(this);
        editTcrud.setVisible(true);
    }//GEN-LAST:event_mnugestTodoActionPerformed

    private void mnuCtodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCtodoActionPerformed
       TodoEDIT editT = new TodoEDIT(this,true,new ToDo());
       editT.setLocationRelativeTo(this);
       editT.setVisible(true);
    }//GEN-LAST:event_mnuCtodoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuCtodo;
    private javax.swing.JMenu mnuToDo;
    private javax.swing.JMenuItem mnucreacat;
    private javax.swing.JMenuItem mnugestTodo;
    private javax.swing.JMenuItem mnugestcat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onCreate(Categoria c) {
        JOptionPane.showMessageDialog(this, "Categoria Salvata");
    }

    @Override
    public void onUpdate(Categoria c) {
        JOptionPane.showMessageDialog(this, "Categoria Modificata e Salvata");
    }

    @Override
    public void onDelete(Categoria c) {
        JOptionPane.showMessageDialog(this, "Categoria Eliminata");
    }
}
