/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.java858.jpacrud.todoapp.GUI;

import it.java858.jpacrud.todoapp.entity.ToDo;
import it.java858.jpacrud.todoapp.service.ToDoService;
import it.java858.jpacrud.todoapp.GUI.CategoriaTM;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author tss
 */
public class TodoCRUD extends javax.swing.JDialog {

    TodoTM todoTM;
    /**
     * Creates new form TodoCRUD
     */
    public TodoCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        todoTM = new TodoTM(ToDoService.Estrai());
        tbltodo.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tbltodo.setModel(todoTM);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltodo = new javax.swing.JTable();
        cmdMod = new javax.swing.JButton();
        cmdCancella = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbltodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltodo);

        cmdMod.setText("Modifica");
        cmdMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModActionPerformed(evt);
            }
        });

        cmdCancella.setText("Cancella");
        cmdCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancellaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(cmdMod)
                        .addGap(188, 188, 188)
                        .addComponent(cmdCancella))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMod)
                    .addComponent(cmdCancella))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancellaActionPerformed
      ToDo Toremove;
      Toremove = todoTM.get(tbltodo.convertRowIndexToModel(tbltodo.getSelectedRow()));
      ToDoService.EliminaT(Toremove);
      todoTM.changeDATA(ToDoService.Estrai());
        JOptionPane.showMessageDialog(this, "ToDo Salvato");
        close();
    }//GEN-LAST:event_cmdCancellaActionPerformed

    private void cmdModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModActionPerformed
    ToDo ToModif;
    ToModif = todoTM.get(tbltodo.convertRowIndexToModel(tbltodo.getSelectedRow()));
    TodoEDIT dialog = new TodoEDIT(this, true, ToModif);
    dialog.setVisible(true);
    todoTM.changeDATA(ToDoService.Estrai());
        JOptionPane.showMessageDialog(this, "Categoria Salvata");
    }//GEN-LAST:event_cmdModActionPerformed
     private void close() {
        this.setVisible(false);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancella;
    private javax.swing.JButton cmdMod;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltodo;
    // End of variables declaration//GEN-END:variables
}
